# Generated by Django 2.1.5 on 2019-01-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0002_manpowerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerdetail',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
