# Generated by Django 2.1.5 on 2019-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('image', models.ImageField(upload_to='raw_materials/images')),
                ('unit_of_mesure', models.CharField(choices=[('m', 'Metros'), ('g', 'Gramos'), ('l', 'Litros'), ('m^2', 'Metros cuadrados'), ('m^3', 'Metros cúbicos')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
