# Generated by Django 2.1.5 on 2019-01-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='raw_materials/images'),
        ),
    ]
