# Generated by Django 2.1.5 on 2019-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0003_auto_20190126_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialdetail',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
